name: Generate GitHub Stats SVG

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create stats folder
        run: mkdir -p stats

      - name: Download GitHub Stats SVG
        run: |
          curl -o stats/github-stats.svg "https://raw.githubusercontent.com/vigneshkattamudi/vigneshkattamudi/main/stats/github-stats.svg"
          curl -o stats/top-langs.svg "https://raw.githubusercontent.com/vigneshkattamudi/vigneshkattamudi/main/stats/top-langs.svg"

      - name: Commit and push SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats SVGs"
          file_pattern: stats/*.svg
          commit_user_name: "GitHub Actions"
          commit_user_email: "github-actions@users.noreply.github.com"
          token: ${{ secrets.PAT_TOKEN }}

